name: Deploy to Netlify on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - 'feature/*'
      - 'fix/*'
    paths:
      - 'src/website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Netlify CLI
        uses: netlify/actions/cli@main
        with:
          cli-version: 'latest'

      - name: Deploy to Netlify (Preview)
        id: netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy \
            --dir=src/website \
            --site=$NETLIFY_SITE_ID \
            --auth=$NETLIFY_AUTH_TOKEN \
            --message "Deploy preview for PR #${{ github.event.pull_request.number }}" \
            --json > deploy-info.json
          echo "DEPLOY_URL=$(jq -r .deploy_url deploy-info.json)" >> $GITHUB_ENV

      - name: Comment deploy preview URL on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const pr = context.payload.pull_request.number;
            const url = process.env.DEPLOY_URL;
            if (url) {
              github.rest.issues.createComment({
                issue_number: pr,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `🚀 Netlify Deploy Preview: [${url}](${url})`
              });
            }